Repository SOS-RS/frontend, pull requests merged in 2024-05, with the labels that each got.

#29 fix: Update README with project progress and instructions
  README.md
Labels: waiting-pr-author

#46 Campo de quantidade adicionado quando adicionar suprimento a um abrigo
  src/components/Chip/types.ts
  src/hooks/useShelter/types.ts
  src/hooks/useShelters/types.ts
  src/pages/CreateSupply/CreateSupply.tsx
  src/pages/EditShelterSupply/EditShelterSupply.tsx
  src/pages/EditShelterSupply/components/SupplyRow/SupplyRow.tsx
  src/pages/EditShelterSupply/components/SupplyRow/types.ts
  src/pages/EditShelterSupply/components/SupplyRowInfo/SupplyRowInfo.tsx
  src/pages/EditShelterSupply/components/SupplyRowInfo/types.ts
  src/pages/Shelter/Shelter.tsx
  src/pages/Shelter/components/ShelterCategoryItems/ShelterCategoryItems.tsx
  src/pages/Shelter/components/ShelterCategoryItems/types.ts
  src/service/shelterSupply/types.ts
Labels: important

#219 fix/ add lucide icons to replace emojis so it works across all browsers
  src/pages/AboutUs/AboutUs.tsx
  src/pages/AboutUs/frontItems.tsx
  src/pages/Home/components/Filter/types.ts
Labels: bug

#280 Feature/botao voltar ao topo
  src/App.tsx
  src/components/BackToTop/BackToTop.tsx
  src/components/BackToTop/index.ts
Labels: waiting-business-requirements

#330 feat: add multi option for priority queryParam
  src/pages/Home/Home.tsx
  src/pages/Home/components/Filter/Filter.tsx
  src/pages/Home/components/Filter/types.ts
Labels: enhancement
